#pragma once

enum class inj_ret
{
	SUCCESSFUL = 0,
	INVALID_PROC_ID,
	FAILED_TO_OPEN_PROCESS,
	FAILED_TO_ALLOCATE,
	INVALID_DOS_HEADER,
	PROC_ID_STOI_EXCEPTION,
	FAILED_TO_OPEN_FILE,
	FAILED_TO_REMOTE_INJECT,
};